---
- hosts: debian
  remote_user: ansible
  become: yes
  vars_files:
    - ../files/dbpassword.yml

  tasks:

  - name: Determinar Distribucion - RedHat/Rocky
    set_fact:
      pkg_mgr: "yum"
    when: ansible_distribution == "RedHat" or ansible_distribution == "Rocky"

  - name: Determinar Distribucion - Ubuntu
    set_fact:
      pkg_mgr: "apt"
    when: ansible_distribution == "Ubuntu"

  - name: Instalacion Server MariaDB - RedHat/Rocky
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - mariadb-server
      - mariadb-client
      - python3-pip
    when: pkg_mgr == "yum"

  - name: Instalacion Server MariaDB - Ubuntu
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - mariadb-server
      - mariadb-client
      - python3-pip
    when: pkg_mgr == "apt"

  - name: Instalacion de PyMySQL con pip
    pip:
      name: PyMySQL
      executable: pip3
      extra_args: --user

  - name: Habilitacion e inicio de Servicio
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Configurar Servidor para que escuche en todas las interfaces
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: bind-address = 0.0.0.0
    notify: Reiniciar servicio MariaDB

  - name: Publicacion de puerto del Servicio - RedHat/Rocky
    firewalld:
     port: 3306/tcp
     permanent: true
     state: enabled
    when: pkg_mgr == "yum"

  - name: Publicacion de puerto del Servicio - Ubuntu
    ufw:
     rule: allow
     port: '3306'
     proto: tcp
    when: pkg_mgr == "apt"


#MySQL Secure Installation
  - name: Actualizacion de root password de MariaDB
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: root
      login_password: "{{ rootpass }}"
      check_implicit_admin: yes 
      name: root
      host: "{{ item }}"
      password: "{{ rootpass }}" 
    loop:
      - 127.0.0.1
      - localhost
      - 172.17.0.%

  - name: Borrado de login anonimo
    mysql_user:
      login_host: localhost
      login_user: root
      login_password: "{{ rootpass }}"
      name: ""
      host_all: yes
      state: absent

  - name: Borrado de Base de Datos test
    mysql_db:
      login_host: localhost
      login_user: root
      login_password: "{{ rootpass }}"
      name: test
      state: absent

  handlers:
  
  - name: Reiniciar servicio MariaDB
    service:
      name: mariadb
      state: restarted
